### ISSUE TITLE
Release and Publish to Maven Central

### ISSUE THREAD

**Issue by kenfinnigan** [openshiftio/booster-common#1]

**Comment by ALRubinger** [comment]
Request submitted: https://issues.sonatype.org/browse/OSSRH-30232

**Comment by ALRubinger** [comment]
Closing, tracking in planning project https://github.com/openshiftio/appdev-planning/issues/3

**Comment by ALRubinger** [comment]
Reopening, I see now that this is for actually publishing to Maven Central, not just the dependency task listed above.

**Comment by kenfinnigan** [comment]
Resolved with https://github.com/openshiftio/booster-common/commit/53ea6daf08755e32aa32a054edfa10cef1793303
