### ISSUE TITLE
OpenShiftTestAssistant clean up failures

### ISSUE THREAD

**Issue by SlavoKrupa** [openshiftio/booster-common#3]
`OpenShiftTestAssistant#cleanup` fails when the OpenShift instance is remote and bad timing occurs. It happens during deletion of DeploymentConfig because I suppose that it tries to delete *ReplicationController* as well, and replicas are scaled down before deletion. Tests failure contains this message:

```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: 
https://api.devel.xpaas:8443/api/v1/namespaces/skrupa/replicationcontrollers/crud-vertx-1. 
Message: Unable to remove nonexistant key: availableReplicas. 
Received status: Status(apiVersion=v1, code=500, details=null, kind=Status, message=Unable to remove nonexistant key: availableReplicas, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=null, status=Failure, additionalProperties={}).

        at io.openshift.booster.OpenShiftIT.cleanup(OpenShiftIT.java:58)
```

The important part is: *Unable to remove nonexistent key: availableReplicas.* It indicates that cleanup procedure is trying to scale down `availableReplicas` which were already deleted. This fails the tests and whole build process.

Reproduce steps:
* Clone https://github.com/openshiftio-vertx-boosters/vertx-crud-booster
* login to remote openshift instance with medium load
* run (multiple runs may be necessary because it fails just ~ 1 in 3 runs) 
 `mvn clean verify -Popenshift`

**Comment by SlavoKrupa** [comment]
This was partially fixed by #4, but `ReplicationController` instance sometimes are not deleted when failure occurs.

Upgrade of `openshift-client.version` to 2.2.13 seems to fix the issue.

**Comment by Ladicek** [comment]
IIRC, we can't update the OpenShift client library, because the newer version hasn't been productized (yet).

**Comment by SlavoKrupa** [comment]
And also because `vertx-config-kubernetes-configmap` (used in config map booster) depends on `kubernetes-client` version `1.4.34`, which is not API compatible with `2.2.13`.

**Comment by SlavoKrupa** [comment]
Can anyone please release new version ? @cescoffier @kenfinnigan  Integraiton tests in Vert.x CRUD boosters are failing sometimes without this fix. I suppose we need to release new parent version as well ?

**Comment by cescoffier** [comment]
@kenfinnigan WDYT ? I can cut a release.

**Comment by kenfinnigan** [comment]
sure

**Comment by cescoffier** [comment]
Done !
