### ISSUE TITLE
switch OpenShiftTestAssistant to fabric8-arquillan or Arquilllian's Kubernetes/OpenShift support 

### ISSUE THREAD

**Issue by jstrachan** [openshiftio/booster-common#8]
`OpenShiftTestAssistant` doesn't work on kubernetes; nor can it run on OpenShift.io in another namespace (on OpenShift.io we need to run the integration tests in a different namespace to the default, jenkins, namespace due to quota issues) - since it doesn't grok installing ImageStream/ImageStream tags like fabric8-arquillian + Arquillian's openshift support.

Also the arquililan equivalent has lots of nice things; like catching apps that retry a few times on startup due to issues; or capturing the logs of failed pods etc.

I understand `OpenShiftTestAssistant` was a temporary approach until the strategic solution was found. 

We maybe wanna try make Arquillian's Kubernetes/OpenShfit a little more flexible in terms of dependencies & classloaders - as we've seen some issues in the past with mixed versions of things like kubernetes-client and things like spring-cloud; though hopefully we can try align versions much more closely really.

CC @ALRubinger  we mentioned this on the last call

**Comment by jstrachan** [comment]
BTW this is a handy library of assertions we may wanna include by default too? https://github.com/fabric8io/fabric8/tree/master/components/kubernetes-assertions#default-system-test

**Comment by gastaldi** [comment]
+1, we definitely should be using Arquillian for testing. 
Question: What is the equivalent Arquillian project for Kubernetes: Cube or Fabric8-arquillian? 

Also +1 on including the library of assertions in the test layer

**Comment by jstrachan** [comment]
I think the kubernetes parts of Arquillian Cube (it should be Arquillian Kube ;) - are derived from the fabric8-arquillian code base and are probably the long term things to use - hopefully all the things from fabric8-arquillian have made it into Arquiilan Cube now
http://arquillian.org/arquillian-cube/#_kubernetes

**Comment by bartoszmajsak** [comment]
> We maybe wanna try make Arquillian's Kubernetes/OpenShfit a little more flexible in terms of dependencies & classloaders - as we've seen some issues in the past with mixed versions of things like kubernetes-client and things like spring-cloud; though hopefully we can try align versions much more closely really.

This was all discussed already and I believe we have a solution in place already in Cube.

> I think the kubernetes parts of Arquillian Cube (it should be Arquillian Kube ;) - are derived from the fabric8-arquillian code base and are probably the long term things to use - hopefully all the things from fabric8-arquillian have made it into Arquiilan Cube now

We are almost there when it comes to bringing Fabric8 bits to Cube, for more details have a look here 
https://github.com/arquillian/arquillian-cube/issues/704 (there are just few things to close)

As for the overall move from `OpenshiftTestAssistant` to Cube, we are going to make it happen soon. Here's the relevant JIRA to watch https://issues.jboss.org/projects/OBST/issues/OBST-288

Looping in Alex (@lordofthejars).

**Comment by lordofthejars** [comment]
About kubernetes clients, this is already fixed by shading kubernetes client inside cube. Then as Bartosz mentioned there is the PR 704 which is WIP and after that all things that were in fabric8-arquillian will be ported on c(k)ube.

**Comment by lordofthejars** [comment]
To have it here as well, currently you can inject kubernetes client on any test. So with this in mind any helper class that you need can be put in Arquillian Cube project and then with a PR we can just discuss the best place to put it.

**Comment by jstrachan** [comment]
@lordofthejars awesome!

**Comment by lordofthejars** [comment]
It is explained here http://arquillian.org/arquillian-cube/#_resource_providers

**Comment by jstrachan** [comment]
this is still a blocker of being able to use integration tests on OSIO/fabric8. Has there been any progress moving `OpenShiftTestAssistant` to use Arquillian Cube?

**Comment by bartoszmajsak** [comment]
Stuff I found accidentally on Monday: https://github.com/openshiftio/appdev-planning/issues/43

I think this reflects the current situation.

**Comment by Ladicek** [comment]
Correct. There's just too many trackers :-/

**Comment by bartoszmajsak** [comment]
Let's work on arquillian/arquillian-cube#743 then.

**Comment by jstrachan** [comment]
@Ladicek agreed ;)

**Comment by bartoszmajsak** [comment]
@Ladicek do we want to break down to each booster migration and track until completion to resolve this issue? Do you have some issues on your side we can reference from here?

**Comment by Ladicek** [comment]
@bartoszmajsak Uh oh... Well on WildFly Swarm side, we're done. I think Vert.x should be done sometimes this week (@spisiakm?), and on Spring Boot front, I don't know the status but @alesj is working on that.

**Comment by lordofthejars** [comment]
@spisiakm  @alesj if you find anything rise a question or open an issue in github or ping me in mattermost. The final idea is to have arq CE and cube be one project, so any effort that we can do in this direction is more than welcome.

**Comment by spisiakm** [comment]
@lordofthejars @bartoszmajsak Hi guys, I have a problem creating a rolebinding with Arquillian Cube before the tests are run, see https://github.com/arquillian/arquillian-cube/issues/835

**Comment by bartoszmajsak** [comment]
This can be closed now @gastaldi  @Ladicek @spisiakm?

**Comment by cescoffier** [comment]
@bartoszmajsak Yes, it can be closed as all the boosters have switched to Cube. (The last switched happened 2 weeks ago). However, the way it uses / configures Cube may not allow using it on OpenShift.io. It should be checked. However, I would be in favor of opening another issue if another issue pops up.
