### ISSUE TITLE
Configurable new version suffix

### ISSUE THREAD

**Issue by gytis** [openshiftio/booster-common#9]
Is it possible to have a new version suffix configurable? At the moment it's set to be a {number}-SNAPSHOT (https://github.com/openshiftio/booster-common/blob/master/release-script/booster-release.sh#L35). We're going to name prod tags as v1-redhat and next version should be 2-redhat-SNAPSHOT.

**Comment by cescoffier** [comment]
I need to check how to do that. Parsing the version number is going to be a bit more complicated. I can try to parse only the first part (til the first `-`) of the String (like "1" in `1-redhat-SNAPSHOT`) and try to extract the "suffix" automatically.

**Comment by cescoffier** [comment]
Any deadline for this ?

**Comment by gytis** [comment]
No I can use the script as is for now so no rush. Last time I just modified the script locally in this line https://github.com/openshiftio/booster-common/blob/master/release-script/booster-release.sh#L35 to add -redhat-SNAPSHOT instead of just -SNAPSHOT.

**Comment by cescoffier** [comment]
Fixed in #10
